

server:
  port: 8582

spring:
  # JSP 경로 설정
  mvc:
    view:
      prefix: /WEB-INF/views
      suffix: .jsp
      
  # DB 연결정보
  datasource:
    url: jdbc:oracle:thin:@project-db-campus.smhrd.com:1524:xe
    username: royal
    password: r1234
    driver-class-name: oracle.jdbc.OracleDriver
